package com.example.learning3.ui.theme.colors

import androidx.compose.ui.graphics.Color

val blue_theme_light_primary = Color(0xFF006492)
val blue_theme_light_onPrimary = Color(0xFFFFFFFF)
val blue_theme_light_primaryContainer = Color(0xFFC9E6FF)
val blue_theme_light_onPrimaryContainer = Color(0xFF001E2F)
val blue_theme_light_secondary = Color(0xFF50606E)
val blue_theme_light_onSecondary = Color(0xFFFFFFFF)
val blue_theme_light_secondaryContainer = Color(0xFFD3E5F5)
val blue_theme_light_onSecondaryContainer = Color(0xFF0C1D29)
val blue_theme_light_tertiary = Color(0xFF64597B)
val blue_theme_light_onTertiary = Color(0xFFFFFFFF)
val blue_theme_light_tertiaryContainer = Color(0xFFEADDFF)
val blue_theme_light_onTertiaryContainer = Color(0xFF201634)
val blue_theme_light_error = Color(0xFFBA1A1A)
val blue_theme_light_errorContainer = Color(0xFFFFDAD6)
val blue_theme_light_onError = Color(0xFFFFFFFF)
val blue_theme_light_onErrorContainer = Color(0xFF410002)
val blue_theme_light_background = Color(0xFFFCFCFF)
val blue_theme_light_onBackground = Color(0xFF1A1C1E)
val blue_theme_light_surface = Color(0xFFFCFCFF)
val blue_theme_light_onSurface = Color(0xFF1A1C1E)
val blue_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val blue_theme_light_onSurfaceVariant = Color(0xFF41474D)
val blue_theme_light_outline = Color(0xFF72787E)
val blue_theme_light_inverseOnSurface = Color(0xFFF0F0F3)
val blue_theme_light_inverseSurface = Color(0xFF2E3133)
val blue_theme_light_inversePrimary = Color(0xFF8BCEFF)
val blue_theme_light_shadow = Color(0xFF000000)
val blue_theme_light_surfaceTint = Color(0xFF006492)
val blue_theme_light_outlineVariant = Color(0xFFC1C7CE)
val blue_theme_light_scrim = Color(0xFF000000)

val blue_theme_dark_primary = Color(0xFF8BCEFF)
val blue_theme_dark_onPrimary = Color(0xFF00344E)
val blue_theme_dark_primaryContainer = Color(0xFF004B6F)
val blue_theme_dark_onPrimaryContainer = Color(0xFFC9E6FF)
val blue_theme_dark_secondary = Color(0xFFB7C9D9)
val blue_theme_dark_onSecondary = Color(0xFF22323F)
val blue_theme_dark_secondaryContainer = Color(0xFF384956)
val blue_theme_dark_onSecondaryContainer = Color(0xFFD3E5F5)
val blue_theme_dark_tertiary = Color(0xFFCFC0E8)
val blue_theme_dark_onTertiary = Color(0xFF352B4B)
val blue_theme_dark_tertiaryContainer = Color(0xFF4C4162)
val blue_theme_dark_onTertiaryContainer = Color(0xFFEADDFF)
val blue_theme_dark_error = Color(0xFFFFB4AB)
val blue_theme_dark_errorContainer = Color(0xFF93000A)
val blue_theme_dark_onError = Color(0xFF690005)
val blue_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val blue_theme_dark_background = Color(0xFF1A1C1E)
val blue_theme_dark_onBackground = Color(0xFFE2E2E5)
val blue_theme_dark_surface = Color(0xFF1A1C1E)
val blue_theme_dark_onSurface = Color(0xFFE2E2E5)
val blue_theme_dark_surfaceVariant = Color(0xFF41474D)
val blue_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val blue_theme_dark_outline = Color(0xFF8B9198)
val blue_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val blue_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val blue_theme_dark_inversePrimary = Color(0xFF006492)
val blue_theme_dark_shadow = Color(0xFF000000)
val blue_theme_dark_surfaceTint = Color(0xFF8BCEFF)
val blue_theme_dark_outlineVariant = Color(0xFF41474D)
val blue_theme_dark_scrim = Color(0xFF000000)


val blue_seed = Color(0xFF006593)