package com.example.learning3.ui.theme.colors

import androidx.compose.ui.graphics.Color

val brown_theme_light_primary = Color(0xFF805600)
val brown_theme_light_onPrimary = Color(0xFFFFFFFF)
val brown_theme_light_primaryContainer = Color(0xFFFFDDB0)
val brown_theme_light_onPrimaryContainer = Color(0xFF281800)
val brown_theme_light_secondary = Color(0xFF6F5B40)
val brown_theme_light_onSecondary = Color(0xFFFFFFFF)
val brown_theme_light_secondaryContainer = Color(0xFFF9DEBB)
val brown_theme_light_onSecondaryContainer = Color(0xFF261904)
val brown_theme_light_tertiary = Color(0xFF506441)
val brown_theme_light_onTertiary = Color(0xFFFFFFFF)
val brown_theme_light_tertiaryContainer = Color(0xFFD2EABD)
val brown_theme_light_onTertiaryContainer = Color(0xFF0E2004)
val brown_theme_light_error = Color(0xFFBA1A1A)
val brown_theme_light_errorContainer = Color(0xFFFFDAD6)
val brown_theme_light_onError = Color(0xFFFFFFFF)
val brown_theme_light_onErrorContainer = Color(0xFF410002)
val brown_theme_light_background = Color(0xFFFFFBFF)
val brown_theme_light_onBackground = Color(0xFF1F1B16)
val brown_theme_light_surface = Color(0xFFFFFBFF)
val brown_theme_light_onSurface = Color(0xFF1F1B16)
val brown_theme_light_surfaceVariant = Color(0xFFEFE0CF)
val brown_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val brown_theme_light_outline = Color(0xFF817567)
val brown_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val brown_theme_light_inverseSurface = Color(0xFF34302A)
val brown_theme_light_inversePrimary = Color(0xFFFDBA4B)
val brown_theme_light_shadow = Color(0xFF000000)
val brown_theme_light_surfaceTint = Color(0xFF805600)
val brown_theme_light_outlineVariant = Color(0xFFD2C4B4)
val brown_theme_light_scrim = Color(0xFF000000)

val brown_theme_dark_primary = Color(0xFFFDBA4B)
val brown_theme_dark_onPrimary = Color(0xFF442C00)
val brown_theme_dark_primaryContainer = Color(0xFF614000)
val brown_theme_dark_onPrimaryContainer = Color(0xFFFFDDB0)
val brown_theme_dark_secondary = Color(0xFFDCC3A1)
val brown_theme_dark_onSecondary = Color(0xFF3D2E16)
val brown_theme_dark_secondaryContainer = Color(0xFF55442A)
val brown_theme_dark_onSecondaryContainer = Color(0xFFF9DEBB)
val brown_theme_dark_tertiary = Color(0xFFB6CEA3)
val brown_theme_dark_onTertiary = Color(0xFF233517)
val brown_theme_dark_tertiaryContainer = Color(0xFF394C2B)
val brown_theme_dark_onTertiaryContainer = Color(0xFFD2EABD)
val brown_theme_dark_error = Color(0xFFFFB4AB)
val brown_theme_dark_errorContainer = Color(0xFF93000A)
val brown_theme_dark_onError = Color(0xFF690005)
val brown_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val brown_theme_dark_background = Color(0xFF1F1B16)
val brown_theme_dark_onBackground = Color(0xFFEAE1D9)
val brown_theme_dark_surface = Color(0xFF1F1B16)
val brown_theme_dark_onSurface = Color(0xFFEAE1D9)
val brown_theme_dark_surfaceVariant = Color(0xFF4F4539)
val brown_theme_dark_onSurfaceVariant = Color(0xFFD2C4B4)
val brown_theme_dark_outline = Color(0xFF9B8F80)
val brown_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val brown_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val brown_theme_dark_inversePrimary = Color(0xFF805600)
val brown_theme_dark_shadow = Color(0xFF000000)
val brown_theme_dark_surfaceTint = Color(0xFFFDBA4B)
val brown_theme_dark_outlineVariant = Color(0xFF4F4539)
val brown_theme_dark_scrim = Color(0xFF000000)


val brown_seed = Color(0xFF805600)