package com.example.learning3.ui.theme.colors

import androidx.compose.ui.graphics.Color

val pink_theme_light_primary = Color(0xFFB80A63)
val pink_theme_light_onPrimary = Color(0xFFFFFFFF)
val pink_theme_light_primaryContainer = Color(0xFFFFD9E2)
val pink_theme_light_onPrimaryContainer = Color(0xFF3E001D)
val pink_theme_light_secondary = Color(0xFF74565F)
val pink_theme_light_onSecondary = Color(0xFFFFFFFF)
val pink_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val pink_theme_light_onSecondaryContainer = Color(0xFF2B151C)
val pink_theme_light_tertiary = Color(0xFF7C5635)
val pink_theme_light_onTertiary = Color(0xFFFFFFFF)
val pink_theme_light_tertiaryContainer = Color(0xFFFFDCC1)
val pink_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val pink_theme_light_error = Color(0xFFBA1A1A)
val pink_theme_light_errorContainer = Color(0xFFFFDAD6)
val pink_theme_light_onError = Color(0xFFFFFFFF)
val pink_theme_light_onErrorContainer = Color(0xFF410002)
val pink_theme_light_background = Color(0xFFFFFBFF)
val pink_theme_light_onBackground = Color(0xFF201A1B)
val pink_theme_light_surface = Color(0xFFFFFBFF)
val pink_theme_light_onSurface = Color(0xFF201A1B)
val pink_theme_light_surfaceVariant = Color(0xFFF2DDE1)
val pink_theme_light_onSurfaceVariant = Color(0xFF514347)
val pink_theme_light_outline = Color(0xFF837377)
val pink_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
val pink_theme_light_inverseSurface = Color(0xFF352F30)
val pink_theme_light_inversePrimary = Color(0xFFFFB1C8)
val pink_theme_light_shadow = Color(0xFF000000)
val pink_theme_light_surfaceTint = Color(0xFFB80A63)
val pink_theme_light_outlineVariant = Color(0xFFD5C2C6)
val pink_theme_light_scrim = Color(0xFF000000)

val pink_theme_dark_primary = Color(0xFFFFB1C8)
val pink_theme_dark_onPrimary = Color(0xFF650033)
val pink_theme_dark_primaryContainer = Color(0xFF8E004A)
val pink_theme_dark_onPrimaryContainer = Color(0xFFFFD9E2)
val pink_theme_dark_secondary = Color(0xFFE3BDC6)
val pink_theme_dark_onSecondary = Color(0xFF422931)
val pink_theme_dark_secondaryContainer = Color(0xFF5A3F47)
val pink_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val pink_theme_dark_tertiary = Color(0xFFEFBD94)
val pink_theme_dark_onTertiary = Color(0xFF48290B)
val pink_theme_dark_tertiaryContainer = Color(0xFF613F20)
val pink_theme_dark_onTertiaryContainer = Color(0xFFFFDCC1)
val pink_theme_dark_error = Color(0xFFFFB4AB)
val pink_theme_dark_errorContainer = Color(0xFF93000A)
val pink_theme_dark_onError = Color(0xFF690005)
val pink_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val pink_theme_dark_background = Color(0xFF201A1B)
val pink_theme_dark_onBackground = Color(0xFFEBE0E1)
val pink_theme_dark_surface = Color(0xFF201A1B)
val pink_theme_dark_onSurface = Color(0xFFEBE0E1)
val pink_theme_dark_surfaceVariant = Color(0xFF514347)
val pink_theme_dark_onSurfaceVariant = Color(0xFFD5C2C6)
val pink_theme_dark_outline = Color(0xFF9E8C90)
val pink_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val pink_theme_dark_inverseSurface = Color(0xFFEBE0E1)
val pink_theme_dark_inversePrimary = Color(0xFFB80A63)
val pink_theme_dark_shadow = Color(0xFF000000)
val pink_theme_dark_surfaceTint = Color(0xFFFFB1C8)
val pink_theme_dark_outlineVariant = Color(0xFF514347)
val pink_theme_dark_scrim = Color(0xFF000000)


val pink_seed = Color(0xFFB80B63)