package com.example.learning3.ui.theme.colors

import androidx.compose.ui.graphics.Color

val purple_theme_light_primary = Color(0xFF8B1BD9)
val purple_theme_light_onPrimary = Color(0xFFFFFFFF)
val purple_theme_light_primaryContainer = Color(0xFFF2DAFF)
val purple_theme_light_onPrimaryContainer = Color(0xFF2E004E)
val purple_theme_light_secondary = Color(0xFF675A6E)
val purple_theme_light_onSecondary = Color(0xFFFFFFFF)
val purple_theme_light_secondaryContainer = Color(0xFFEEDDF6)
val purple_theme_light_onSecondaryContainer = Color(0xFF221829)
val purple_theme_light_tertiary = Color(0xFF815155)
val purple_theme_light_onTertiary = Color(0xFFFFFFFF)
val purple_theme_light_tertiaryContainer = Color(0xFFFFDADB)
val purple_theme_light_onTertiaryContainer = Color(0xFF321015)
val purple_theme_light_error = Color(0xFFBA1A1A)
val purple_theme_light_errorContainer = Color(0xFFFFDAD6)
val purple_theme_light_onError = Color(0xFFFFFFFF)
val purple_theme_light_onErrorContainer = Color(0xFF410002)
val purple_theme_light_background = Color(0xFFFFFBFF)
val purple_theme_light_onBackground = Color(0xFF1D1B1E)
val purple_theme_light_surface = Color(0xFFFFFBFF)
val purple_theme_light_onSurface = Color(0xFF1D1B1E)
val purple_theme_light_surfaceVariant = Color(0xFFE9DFEA)
val purple_theme_light_onSurfaceVariant = Color(0xFF4B454D)
val purple_theme_light_outline = Color(0xFF7C757E)
val purple_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val purple_theme_light_inverseSurface = Color(0xFF322F33)
val purple_theme_light_inversePrimary = Color(0xFFE0B6FF)
val purple_theme_light_shadow = Color(0xFF000000)
val purple_theme_light_surfaceTint = Color(0xFF8B1BD9)
val purple_theme_light_outlineVariant = Color(0xFFCDC3CE)
val purple_theme_light_scrim = Color(0xFF000000)

val purple_theme_dark_primary = Color(0xFFE0B6FF)
val purple_theme_dark_onPrimary = Color(0xFF4C007C)
val purple_theme_dark_primaryContainer = Color(0xFF6C00AE)
val purple_theme_dark_onPrimaryContainer = Color(0xFFF2DAFF)
val purple_theme_dark_secondary = Color(0xFFD1C1D9)
val purple_theme_dark_onSecondary = Color(0xFF372C3F)
val purple_theme_dark_secondaryContainer = Color(0xFF4E4256)
val purple_theme_dark_onSecondaryContainer = Color(0xFFEEDDF6)
val purple_theme_dark_tertiary = Color(0xFFF4B7BB)
val purple_theme_dark_onTertiary = Color(0xFF4C2529)
val purple_theme_dark_tertiaryContainer = Color(0xFF663A3F)
val purple_theme_dark_onTertiaryContainer = Color(0xFFFFDADB)
val purple_theme_dark_error = Color(0xFFFFB4AB)
val purple_theme_dark_errorContainer = Color(0xFF93000A)
val purple_theme_dark_onError = Color(0xFF690005)
val purple_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val purple_theme_dark_background = Color(0xFF1D1B1E)
val purple_theme_dark_onBackground = Color(0xFFE7E1E5)
val purple_theme_dark_surface = Color(0xFF1D1B1E)
val purple_theme_dark_onSurface = Color(0xFFE7E1E5)
val purple_theme_dark_surfaceVariant = Color(0xFF4B454D)
val purple_theme_dark_onSurfaceVariant = Color(0xFFCDC3CE)
val purple_theme_dark_outline = Color(0xFF968E98)
val purple_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val purple_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val purple_theme_dark_inversePrimary = Color(0xFF8B1BD9)
val purple_theme_dark_shadow = Color(0xFF000000)
val purple_theme_dark_surfaceTint = Color(0xFFE0B6FF)
val purple_theme_dark_outlineVariant = Color(0xFF4B454D)
val purple_theme_dark_scrim = Color(0xFF000000)


val purple_seed = Color(0xFF8B1CD9)